getopS

diff --git a/src/slexfe b/src/slexfe
--- a/src/slexfe
+++ b/src/slexfe
@@ -56,43 +56,39 @@ keys=""
 extra=""
 context=""
 
-OPTIONS=$(getopt -o c:s:d:k:e:x:F:h --long conf:,slangroom-contract:,data:,keys:,extra:,context:,filename:,help -n 'parse-options' -- "$@")
-if [ $? -ne 0 ]; then
-    printf "Failed to parse options." >&2
-    exit 1
-fi
-eval set -- "$OPTIONS"
-
-while true; do
-    case "$1" in
-        -c|--conf)
-            conf=$(encode_base64 "$2"); shift 2 ;;
-        -s|--slangroom-contract)
-            slangroom_contract=$(encode_base64 "$2"); shift 2 ;;
-        -d|--data)
-            data=$(encode_json_base64 "$2"); shift 2 ;;
-        -k|--keys)
-            keys=$(encode_json_base64 "$2"); shift 2 ;;
-        -e|--extra)
-            extra=$(encode_json_base64 "$2"); shift 2 ;;
-        -x|--context)
-            context=$(encode_base64 "$2"); shift 2 ;;
-        -F|--filename)
-            conf=$(encode_base64 "${2}.conf")
-            slangroom_contract=$(encode_base64 "${2}.slang")
-            data=$(encode_json_base64 "${2}.data.json")
-            keys=$(encode_json_base64 "${2}.keys.json")
-            extra=$(encode_json_base64 "${2}.extra.json")
-            context=$(encode_base64 "${2}.context")
-            shift 2 ;;
-        -h|--help)
+while getopts "c:s:d:k:e:x:F:h" opt; do
+    case ${opt} in
+        c)
+            conf=$(encode_base64 "${OPTARG}");;
+        s)
+            slangroom_contract=$(encode_base64 "${OPTARG}");;
+        d)
+            data=$(encode_json_base64 "${OPTARG}");;
+        k)
+            keys=$(encode_json_base64 "${OPTARG}");;
+        e)
+            extra=$(encode_json_base64 "${OPTARG}");;
+        x)
+            context=$(encode_base64 "${OPTARG}");;
+        F)
+            conf=$(encode_base64 "${OPTARG}.conf")
+            slangroom_contract=$(encode_base64 "${OPTARG}.slang")
+            data=$(encode_json_base64 "${OPTARG}.data.json")
+            keys=$(encode_json_base64 "${OPTARG}.keys.json")
+            extra=$(encode_json_base64 "${OPTARG}.extra.json")
+            context=$(encode_base64 "${OPTARG}.context");;
+        h)
             print_help ;;
-        --)
-            shift; break ;;
-        *)
-            printf "Internal error!"; exit 1 ;;
+        \?)
+            printf "Invalid option: -${OPTARG}" >&2
+            exit 1 ;;
+        :)
+            printf "Option -${OPTARG} requires an argument." >&2
+            exit 1 ;;
     esac
 done
+shift $((OPTIND -1))
+
 
 # if slangroom-contract is empty, read it from stdin
 if [ -z "$slangroom_contract" ]; then
